name: Sqlverifier API Testing

on:
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '25 3 * * *'

jobs:
  run-sqlverifier-api-tests:
    name: Execute Sqlverifier API tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Newman and reporters
        run: |
          npm install -g newman
          npm install -g newman-reporter-allure

      - name: Create directory for test results
        run: mkdir -p testResults

      - name: Execute Postman collection
        run:
          newman run sqlverifier.postman_collection.json -e sqlverifier-staging.postman_environment.json -r cli,allure --reporter-allure-export testResults/allure-results > testResults/output.txt
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test reports
          path: testResults

      - name: Checkout test history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: testResults/allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
